### ISSUE TITLE
make plugin work with wp cli login

### ISSUE THREAD

**Issue by chrillep** [Melapress/wp-2fa#82]
steps to reproduce.

install wp login cli

https://aaemnnost.tv/wp-cli-commands/login/
https://github.com/aaemnnosttv/wp-cli-login-command

try and login with a user that exists

```shell
wp login as 1
```
see that the generated login link **WORKS**

install and setup 2fa plugin

try and login with a user that exists

```shell
wp login as 1
```

see that the generated login link **FAILS**

🙂

**Comment by chrillep** [comment]
https://wordpress.org/support/topic/make-plugin-work-with-wp-cli-login/

**Comment by robert81** [comment]
As explained on the support forums.
